### ISSUE TITLE
i can't initiate tweakpane

### ISSUE THREAD

**Issue by Vince66000** [gsimone/use-tweaks#54]
Hi,

i'm encoutring an issue when i install Tweakpane and try to use it : 

`const tweakpane = require('tweakpane');`

`const createPane = () => {
    const pane = new tweakpane.Pane();
}

createPane();`

i have this error : 

C:\wamp64\www\cours code créatif\skteches\node_modules\tweakpane\dist\tweakpane.js:7791
export { BladeApi, ButtonApi, FolderApi, ListBladeApi, ListInputBindingApi, Pane, Semver, SeparatorBladeApi, SliderBladeApi, SliderInputBindingApi, TabApi, TabPageApi, TextBladeApi, TpChangeEvent, VERSION };
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

anybody can help me please ?

**Comment by cocopon** [comment]
Here is the repository for `use-tweaks`, not `tweakpane`. Please report it to the right place:
https://github.com/cocopon/tweakpane/issues

Anyway, additional information is needed to investigate the issue.

- OS
- Node.js version
- Tweakpane version
- Package bundler
- etc.
